const legalKnowledgeBase = {
  // Existing legal knowledge base for Indian law
  "fundamental rights": "Under the Indian Constitution, fundamental rights include Right to Equality (Articles 14-18), Right to Freedom (Articles 19-22), Right against Exploitation (Articles 23-24), Right to Freedom of Religion (Articles 25-28), Cultural and Educational Rights (Articles 29-30), and Right to Constitutional Remedies (Article 32).",
  "right to equality": "Right to Equality (Articles 14-18) guarantees equality before law, prohibition of discrimination, equality of opportunity in public employment, abolition of untouchability, and abolition of titles.",
  "article 14": "Article 14 of the Indian Constitution guarantees equality before the law and equal protection of the laws to all persons within the territory of India.",
  "right to freedom": "Right to Freedom (Articles 19-22) includes freedom of speech and expression, assembly, association, movement, residence, and profession, subject to reasonable restrictions.",
  
  // RTI
  "rti": "The Right to Information Act, 2005 empowers Indian citizens to request information from any public authority. The application fee is ₹10, and you should receive a response within 30 days. For BPL cardholders, no fee is required. You can file applications online or physically to the Public Information Officer of the relevant department.",
  "right to information act": "The Right to Information Act, 2005 empowers Indian citizens to request information from any public authority. The application fee is ₹10, and you should receive a response within 30 days. For BPL cardholders, no fee is required. You can file applications online or physically to the Public Information Officer of the relevant department.",

  "file rti": "To file an RTI: 1) Identify the department holding the information, 2) Write an application addressed to the PIO (Public Information Officer), 3) Pay the fee of ₹10 (fee exempted for BPL cardholders), 4) Submit in person, by post, or online through rtionline.gov.in. You should receive a response within 30 days.",
  
  // Family Law
  "divorce": "In India, divorce can be obtained under the Hindu Marriage Act, Special Marriage Act, Muslim Personal Law, or other personal laws depending on your religion. Grounds include cruelty, desertion (2+ years), conversion to another religion, mental disorder, communicable disease, presumption of death, and mutual consent. Mutual consent divorce typically takes 6-18 months.",
  "divorce process": "The divorce process in India generally involves: 1) Filing a petition in family court, 2) Court issues notice to the spouse, 3) Appearance and response by the spouse, 4) Mediation attempts, 5) Evidence presentation if contested, 6) Final arguments, 7) Court judgment. For mutual consent divorces, there's a mandatory 6-month cooling period between first and second motion.",
  "marriage registration": "Marriage registration in India can be done under either the Hindu Marriage Act or the Special Marriage Act. Documents required typically include: proof of age, residence proof, photographs, and marriage invitation card (if applicable). The process involves submitting an application to the local Sub-Registrar's office with the required documents and fee.",
  "adoption": "Adoption in India is governed by the Hindu Adoption and Maintenance Act (for Hindus) and the Juvenile Justice Act (secular law applicable to all). Prospective parents must register with the Central Adoption Resource Authority (CARA) and follow their procedure. Inter-country adoptions are also regulated by CARA in compliance with the Hague Convention.",
  
  // Property Law
  "property": "Property disputes in India are addressed through civil courts. For effective resolution, maintain proper documentation including sale deeds, gift deeds, property tax receipts, mutation records, and inheritance documents. Issues like boundary disputes, title disputes, and ancestral property disputes are common and may require separate lawsuit proceedings.",
  "property inheritance": "Property inheritance in India is governed by personal laws based on religion. For Hindus, the Hindu Succession Act applies, with amendments in 2005 giving equal rights to daughters in ancestral property. Muslims follow Sharia law with different rules for Sunni and Shia communities. Christians and Parsis follow the Indian Succession Act.",
  "tenant rights": "Tenant rights in India are governed by state-specific Rent Control Acts. Generally, tenants have rights to: 1) Proper rent receipts, 2) Notice before eviction, 3) Essential services like water and electricity, 4) Privacy from landlord's intrusion, 5) Protection from arbitrary rent increases as per state laws, 6) Refund of security deposit upon vacating.",
  "land acquisition": "Land acquisition in India is governed by the Right to Fair Compensation and Transparency in Land Acquisition, Rehabilitation and Resettlement Act, 2013. It requires social impact assessment, consent from affected families (70-80% depending on purpose), fair compensation (2-4 times market value in rural areas, 2 times in urban areas), and rehabilitation provisions.",
  
  // Criminal Law
  "murder": "Murder is defined under Section 300 of the Indian Penal Code (IPC) as the intentional killing of another person. It is a non-bailable offense and can lead to severe penalties, including life imprisonment or the death penalty.",
  "kidnapping": "Kidnapping is defined under Sections 359-374 of the IPC. It involves taking or enticing a person away without their consent. Penalties vary based on the circumstances and can include imprisonment.",
  "ransom": "Ransom is the payment demanded for the release of a kidnapped person. Under IPC, it is a serious offense and can lead to imprisonment.",
  "extortion": "Extortion is defined under Section 383 of the IPC. It involves obtaining property or money through coercion or threats. It is punishable by imprisonment.",
  "rape": "Rape is defined under Section 375 of the IPC. It is a serious offense with severe penalties, including life imprisonment. The law has specific provisions to protect the rights of victims.",
  "assault": "Assault is defined under Section 351 of the IPC as an act that causes another person to apprehend the infliction of immediate, unlawful force. It is punishable under the law.",
  "theft": "Theft is defined under Section 378 of the IPC as the act of dishonestly taking movable property out of the possession of another person. It is a non-bailable offense.",
  "fraud": "Fraud is defined under Section 17 of the IPC. It involves deception to secure unfair or unlawful gain. Penalties vary based on the severity of the offense.",
  "domestic violence": "Domestic violence is addressed under the Protection of Women from Domestic Violence Act, 2005. It includes physical, emotional, and economic abuse against women in domestic settings.",
  
  // Additional Legal Concepts
  "legal aid": "Free legal aid in India is available through Legal Services Authorities at National, State, District, and Taluk levels under the Legal Services Authorities Act, 1987. Eligible beneficiaries include women, children, persons with disabilities, victims of trafficking, industrial workmen, SC/ST members, natural disaster victims, and persons with annual income below specified limits. Contact your nearest Legal Services Authority or visit nalsa.gov.in.",
  "pro bono lawyer": "For pro bono legal assistance in India: 1) Contact your State or District Legal Services Authority, 2) Approach NGOs like Human Rights Law Network or iProBono, 3) Check with the Supreme Court Legal Services Committee or High Court Legal Services Committees, 4) Use the Department of Justice's Tele-Law service (14141), 5) Visit the nearest legal aid clinic at law schools.",
  
  // Useful legal terms
  "habeas corpus": "Habeas Corpus is a constitutional remedy under Article 32 and 226 of the Indian Constitution. It's a writ directing a person detaining another to produce the detainee before the court to examine the legality of detention. It safeguards personal liberty against unlawful detention by both state and private individuals.",
  "pil": "Public Interest Litigation (PIL) in India allows any public-spirited person to approach the Supreme Court (Article 32) or High Courts (Article 226) for protection of public interest. PILs address issues affecting public at large, particularly marginalized sections. The court can take suo moto cognizance and has relaxed traditional locus standi requirements for PILs.",
  
  // Expanded Legal Cases and Issues
  "case law": "Case law refers to the law established by the outcome of former court cases. In India, landmark judgments by the Supreme Court and High Courts shape the interpretation of laws and the Constitution. Examples include the Kesavananda Bharati case (1973) which established the Basic Structure doctrine, and the Maneka Gandhi case (1978) which expanded the interpretation of Article 21.",
  "constitutional law": "Constitutional law in India governs the interpretation and implementation of the Constitution. It includes the study of fundamental rights, directive principles, and the structure of government. Key cases include Minerva Mills v. Union of India (1980) which reinforced the supremacy of the Constitution.",
  
  // Cyber Law
  "cyber crime": "To report cybercrimes in India: 1) File a complaint on the National Cyber Crime Reporting Portal (cybercrime.gov.in), 2) Call the Cyber Crime Helpline (1930), 3) Visit the nearest Cyber Crime Police Station, 4) For financial fraud, report within 24 hours for better chance of recovering funds. Common cybercrimes include phishing, identity theft, online harassment, data breach, and financial fraud.",
  "online harassment": "For online harassment in India: 1) Preserve evidence (screenshots, URLs, messages), 2) Report to the platform, 3) File complaint on cybercrime.gov.in or call 1930, 4) File an FIR at local police station mentioning IPC Sections 354A, 354D, 507, 509 and IT Act Sections 66E, 67, 67A as applicable. For immediate assistance against objectionable content, use National Cybercrime Reporting Portal's 'Report & Remove' feature.",
  "data privacy": "Data privacy in India is currently governed by the Information Technology Act, 2000 and the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011. The Digital Personal Data Protection Act, 2023 will provide a more comprehensive framework once fully implemented, giving individuals rights over their personal data and imposing obligations on data processors.",
  
  // Citizenship & Immigration
  "citizenship": "Indian citizenship can be acquired by birth, descent, registration, or naturalization under the Citizenship Act, 1955. For citizenship by registration, one must have resided in India for 7 years. For naturalization, the requirement is 12 years of residence with no more than 12 months absence during the final year. The Citizenship Amendment Act, 2019 created a pathway for certain religious minorities from Afghanistan, Bangladesh, and Pakistan.",
  "oci card": "Overseas Citizen of India (OCI) card provides: 1) Multiple-entry, multi-purpose lifelong visa to India, 2) Exemption from foreigner registration, 3) Parity with NRIs in economic, financial, and educational fields (except property and agricultural land purchases), 4) No voting rights or government jobs. Eligible applicants include former Indian citizens, their descendants up to the 4th generation, and spouses of Indian citizens/OCIs.",
  "visa types": "Common Indian visa types include: Tourist visa (up to 10 years), e-Tourist visa (1-5 years), Business visa (up to 5 years), Employment visa (duration of contract), Student visa (duration of course), Medical visa (up to 1 year), Conference visa (event duration), and Research visa (up to 5 years). Each has specific documentation requirements and restrictions.",
  
  // Wills & Succession
  "will": "A legally valid will in India requires: 1) Testator must be of sound mind and at least 21 years old, 2) Signed by the testator, 3) Attested by two or more witnesses who have seen the testator sign, 4) Witnesses should not be beneficiaries. Registration of wills is optional but recommended. For Muslims, will-making is governed by Islamic law limiting bequests to one-third of property to non-heirs.",
  "probate": "Probate is a court certificate validating a will. In India, it's mandatory in the presidency towns of Kolkata, Mumbai, and Chennai. The process involves: 1) Filing petition in the High Court or District Court with jurisdiction, 2) Submitting original will, death certificate, and other supporting documents, 3) Court issues notice to family members and publishes citation in newspaper, 4) After addressing any objections, the court grants probate.",
  
  // Consumer Rights
  "consumer rights": "Under the Consumer Protection Act, 2019, Indian consumers have the right to: 1) Safety, 2) Information, 3) Choice, 4) Redressal, 5) Consumer education, 6) Protection from unfair trade practices. Complaints can be filed at District, State, or National Consumer Disputes Redressal Commission depending on the claim amount.",
  "consumer complaint": "To file a consumer complaint: 1) Approach the business first with your grievance, 2) If unresolved, file a formal complaint with the appropriate Consumer Commission (District/State/National based on claim amount), 3) Include details of the complaint, supporting documents, and relief sought, 4) Pay the nominal fee, 5) Alternative online filing is available at edaakhil.nic.in.",
  "e-commerce rights": "For e-commerce purchases in India, consumers have rights under the Consumer Protection (E-Commerce) Rules, 2020, including: 1) Clear information about sellers, products, and prices, 2) Cancellation rights, 3) Refund policies, 4) Grievance redressal mechanism, 5) Protection from unfair trade practices like fake reviews. Platforms cannot manipulate prices or misrepresent quality.",
  
  // Employment Law
  "employment": "Employment in India is governed by various laws including the Industrial Disputes Act, Factories Act, Payment of Wages Act, and more recently, the Code on Wages, 2019. These laws cover minimum wages, working hours (typically 48 hours/week), overtime payment, leave entitlement, termination procedures, and social security benefits.",
  "maternity benefits": "Under the Maternity Benefit (Amendment) Act, 2017, working women in India are entitled to: 1) 26 weeks of paid maternity leave for the first two children (12 weeks for third child onwards), 2) 12 weeks for adoptive and commissioning mothers, 3) Work-from-home options post-leave, 4) Crèche facilities in establishments with 50+ employees, 5) No termination during pregnancy/maternity leave.",
  "sexual harassment": "Workplace sexual harassment in India is addressed by the Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013. Every organization with 10+ employees must have an Internal Complaints Committee. Complaints should be filed within 3 months of the incident. Employers must provide a safe working environment and display the consequences of sexual harassment prominently.",
};

export default legalKnowledgeBase;
