const legalKnowledgeBase = {
  // Existing legal knowledge base for Indian law
  "fundamental rights": "Under the Indian Constitution, fundamental rights include Right to Equality (Articles 14-18), Right to Freedom (Articles 19-22), Right against Exploitation (Articles 23-24), Right to Freedom of Religion (Articles 25-28), Cultural and Educational Rights (Articles 29-30), and Right to Constitutional Remedies (Article 32).",
  "right to equality": "Right to Equality (Articles 14-18) guarantees equality before law, prohibition of discrimination, equality of opportunity in public employment, abolition of untouchability, and abolition of titles.",
  "article 14": "Article 14 of the Indian Constitution guarantees equality before the law and equal protection of the laws to all persons within the territory of India.",
  "right to freedom": "Right to Freedom (Articles 19-22) includes freedom of speech and expression, assembly, association, movement, residence, and profession, subject to reasonable restrictions.",
  
  // RTI
  "rti": "The Right to Information Act, 2005 empowers Indian citizens to request information from any public authority. The application fee is ₹10, and you should receive a response within 30 days. For BPL cardholders, no fee is required. You can file applications online or physically to the Public Information Officer of the relevant department.",
  "right to information act": "The Right to Information Act, 2005 empowers Indian citizens to request information from any public authority. The application fee is ₹10, and you should receive a response within 30 days. For BPL cardholders, no fee is required. You can file applications online or physically to the Public Information Officer of the relevant department.",
  "file rti": "To file an RTI: 1) Identify the department holding the information, 2) Write an application addressed to the PIO (Public Information Officer), 3) Pay the fee of ₹10 (fee exempted for BPL cardholders), 4) Submit in person, by post, or online through rtionline.gov.in. You should receive a response within 30 days.",
  
  // Family Law
  "divorce": "In India, divorce can be obtained under the Hindu Marriage Act, Special Marriage Act, Muslim Personal Law, or other personal laws depending on your religion. Grounds include cruelty, desertion (2+ years), conversion to another religion, mental disorder, communicable disease, presumption of death, and mutual consent. Mutual consent divorce typically takes 6-18 months.",
  "divorce process": "The divorce process in India generally involves: 1) Filing a petition in family court, 2) Court issues notice to the spouse, 3) Appearance and response by the spouse, 4) Mediation attempts, 5) Evidence presentation if contested, 6) Final arguments, 7) Court judgment. For mutual consent divorces, there's a mandatory 6-month cooling period between first and second motion.",
  "marriage registration": "Marriage registration in India can be done under either the Hindu Marriage Act or the Special Marriage Act. Documents required typically include: proof of age, residence proof, photographs, and marriage invitation card (if applicable). The process involves submitting an application to the local Sub-Registrar's office with the required documents and fee.",
  "adoption": "Adoption in India is governed by the Hindu Adoption and Maintenance Act (for Hindus) and the Juvenile Justice Act (secular law applicable to all). Prospective parents must register with the Central Adoption Resource Authority (CARA) and follow their procedure. Inter-country adoptions are also regulated by CARA in compliance with the Hague Convention.",
  
  // Property Law
  "property": "Property disputes in India are addressed through civil courts. For effective resolution, maintain proper documentation including sale deeds, gift deeds, property tax receipts, mutation records, and inheritance documents. Issues like boundary disputes, title disputes, and ancestral property disputes are common and may require separate lawsuit proceedings.",
  "property inheritance": "Property inheritance in India is governed by personal laws based on religion. For Hindus, the Hindu Succession Act applies, with amendments in 2005 giving equal rights to daughters in ancestral property. Muslims follow Sharia law with different rules for Sunni and Shia communities. Christians and Parsis follow the Indian Succession Act.",
  "tenant rights": "Tenant rights in India are governed by state-specific Rent Control Acts. Generally, tenants have rights to: 1) Proper rent receipts, 2) Notice before eviction, 3) Essential services like water and electricity, 4) Privacy from landlord's intrusion, 5) Protection from arbitrary rent increases as per state laws, 6) Refund of security deposit upon vacating.",
  "land acquisition": "Land acquisition in India is governed by the Right to Fair Compensation and Transparency in Land Acquisition, Rehabilitation and Resettlement Act, 2013. It requires social impact assessment, consent from affected families (70-80% depending on purpose), fair compensation (2-4 times market value in rural areas, 2 times in urban areas), and rehabilitation provisions.",
  
  // Criminal Law (UPDATED FROM IPC TO BNS)
  "murder": "Murder under Section 103 of the Bharatiya Nyaya Sanhita (BNS) is punishable with death or imprisonment for life, along with a fine. The section defines murder as causing death with the intention of causing death, or with the intention of causing bodily injury likely to cause death, or with knowledge that the act is likely to cause death. The BNS sets a higher threshold for evidence collection and recognizes different degrees of culpability. Mandatory videography of the crime scene is required for investigation.",
  "kidnapping": "Kidnapping is defined under Sections 136-144 of the Bharatiya Nyaya Sanhita (BNS). Section 137 punishes kidnapping with imprisonment up to 7 years and a fine. Kidnapping for ransom (Section 140) carries 10 years to life imprisonment. Kidnapping a minor carries enhanced penalties of 7-20 years imprisonment. The BNS recognizes different types of kidnapping based on intent and victim characteristics.",
  "ransom": "Kidnapping for ransom under Section 140 of the Bharatiya Nyaya Sanhita (BNS) is punishable with rigorous imprisonment for 10 years up to life imprisonment, and a fine. If the victim dies during captivity, death penalty or life imprisonment may be imposed. The section covers demanding ransom in any form, including money, property, or compliance with other demands in exchange for release of the kidnapped person.",
  "extortion": "Extortion under Section 202 of the Bharatiya Nyaya Sanhita (BNS) is the act of putting any person in fear of harm and dishonestly inducing them to deliver property or valuable security. It is punishable with imprisonment of 3-10 years and a fine. Section 203 covers extortion by threat of accusation of an offense, which carries imprisonment of 10 years and a fine. Extortion by public servants carries enhanced penalties.",
  "rape": "Rape under Section 63 of the Bharatiya Nyaya Sanhita (BNS) is punishable with rigorous imprisonment of 10 years to life, along with a fine. The section defines various acts that constitute rape and clarifies that consent given under fear, intoxication, or misrepresentation does not amount to consent. Gang rape (Section 64) carries 20 years to life imprisonment. Rape of minors and women with disabilities carries enhanced penalties including death in aggravated cases.",
  "assault": "Assault is defined under Section 125 of the Bharatiya Nyaya Sanhita (BNS) as making any gesture or preparation intending or knowing it to be likely to cause apprehension that criminal force will be applied. Punishment for assault or criminal force (Section 126) is imprisonment up to 3 months, or fine up to ₹500, or both. Assault on women with intent to outrage modesty (Section 78) carries stricter punishment of 1-5 years imprisonment and fine.",
  "theft": "Theft under Section 303 of the Bharatiya Nyaya Sanhita (BNS) is punishable with imprisonment up to 3 years, or fine, or both. The section defines theft as dishonestly taking movable property without consent. Section 304 addresses theft in dwelling house, which carries imprisonment up to 7 years and fine. Section 305 covers theft after preparation for causing death or hurt, punishable with imprisonment up to 10 years and fine.",
  "fraud": "Fraud under Section 318 of the Bharatiya Nyaya Sanhita (BNS) is punishable based on the amount involved: up to ₹50,000 carries imprisonment up to 3 years and fine; ₹50,000 to ₹10 lakhs carries imprisonment of 3-5 years and fine; above ₹10 lakhs carries imprisonment of 7 years and fine. The section covers deception to secure unfair gain or to cause wrongful loss to another person. Digital fraud and financial scams are specifically addressed.",
  "domestic violence": "Domestic violence continues to be primarily addressed under the Protection of Women from Domestic Violence Act, 2005, which provides civil remedies including protection orders, residence orders, monetary relief, and custody orders. Criminal aspects are covered under Section 74 of the BNS (cruelty by husband or relatives) with punishment of imprisonment up to 3 years and fine. Severe cases involving grievous hurt carry imprisonment up to 7 years.",
  
  // Detailed BNS Sections for Common Crimes
  "section 103 bns": "Section 103 of the Bharatiya Nyaya Sanhita defines murder as causing the death of a person with the intention of causing death, or with the intention of causing such bodily injury as is likely to cause death, or with the knowledge that such act is likely to cause death. Punishment includes death or imprisonment for life, along with a fine. The section also specifically addresses mob lynching, previously not explicitly covered under the IPC.",
  "section 104 bns": "Section 104 of the Bharatiya Nyaya Sanhita addresses culpable homicide not amounting to murder. It applies when death is caused without premeditation, in a sudden fight, or exceeding the right of private defense. Punishment is imprisonment up to 10 years, or fine, or both. If the act is done with the intention of causing death, imprisonment may extend to life imprisonment.",
  "section 105 bns": "Section 105 of the Bharatiya Nyaya Sanhita addresses death caused by negligence. It punishes any rash or negligent act resulting in death with imprisonment up to 5 years, or fine, or both. This section applies to cases like fatal road accidents caused by negligent driving, medical negligence resulting in death, and industrial accidents caused by negligence.",
  "section 63 bns": "Section 63 of the Bharatiya Nyaya Sanhita defines rape as specific acts against a woman without her consent or with consent obtained through coercion, deception, or when she is unable to understand the nature of the act. Punishment is rigorous imprisonment from 10 years to life, along with a fine. The section has expanded the definition of rape compared to the previous IPC Section 375.",
  "section 64 bns": "Section 64 of the Bharatiya Nyaya Sanhita addresses gang rape, defining it as rape committed by one or more persons acting in concert. Punishment is rigorous imprisonment for 20 years to life, along with fine. The fine must be just and reasonable to meet the medical expenses and rehabilitation of the victim.",
  "section 65 bns": "Section 65 of the Bharatiya Nyaya Sanhita addresses punishment for causing death or resulting in persistent vegetative state while committing rape. The punishment is rigorous imprisonment for life (which means imprisonment for the remainder of the person's natural life) or death, along with a fine.",
  "section 66 bns": "Section 66 of the Bharatiya Nyaya Sanhita specifically criminalizes sexual intercourse by a man with his wife during separation, punishable with imprisonment up to 2 years and fine. It also addresses intercourse by deceitful means or false promise of marriage, punishable with imprisonment up to 10 years and fine.",
  "section 78 bns": "Section 78 of the Bharatiya Nyaya Sanhita addresses assault or use of criminal force on a woman with intent to outrage her modesty. Punishment is imprisonment of 1-5 years and fine. This section enhances the punishment compared to the previous IPC Section 354 and adds clarity to what constitutes outraging modesty.",
  "section 79 bns": "Section 79 of the Bharatiya Nyaya Sanhita addresses sexual harassment. Acts include physical contact, unwelcome sexual overtures, showing pornography, or demanding sexual favors. Punishment is imprisonment up to 3 years, or fine, or both. Subsequent offenses carry enhanced penalties of 5 years imprisonment.",
  "section 136 bns": "Section 136 of the Bharatiya Nyaya Sanhita defines kidnapping as taking or enticing a minor (under 18 years for males, under 18 years for females) without the consent of the guardian, or taking any person by force or deceitful means without their consent. This section consolidates the definitions previously spread across multiple sections of the IPC.",
  "section 137 bns": "Section 137 of the Bharatiya Nyaya Sanhita provides punishment for kidnapping, with imprisonment up to 7 years and fine. The section applies to simple kidnapping cases where there is no additional criminal intent beyond the act of kidnapping itself.",
  "section 140 bns": "Section 140 of the Bharatiya Nyaya Sanhita addresses kidnapping for ransom, with punishment of rigorous imprisonment for 10 years up to life imprisonment, along with fine. If the kidnapped person dies during captivity, the punishment may extend to death penalty or life imprisonment.",
  "section 202 bns": "Section 202 of the Bharatiya Nyaya Sanhita defines extortion as intentionally putting any person in fear of harm and dishonestly inducing them to deliver property or valuable security. Punishment under Section 204 is imprisonment of 3-10 years and fine.",
  "section 303 bns": "Section 303 of the Bharatiya Nyaya Sanhita defines theft as dishonestly taking movable property out of the possession of another person without that person's consent. Punishment is imprisonment up to 3 years, or fine, or both. The section emphasizes the element of dishonest intention.",
  "section 309 bns": "Section 309 of the Bharatiya Nyaya Sanhita defines robbery as theft accompanied by causing or attempting to cause fear of death, hurt, or wrongful restraint. Punishment under Section 311 is rigorous imprisonment of 7-10 years and fine. If committed on a highway between sunset and sunrise, punishment is enhanced.",
  "section 318 bns": "Section 318 of the Bharatiya Nyaya Sanhita addresses cheating and dishonestly inducing delivery of property. Punishment varies based on the amount: up to ₹50,000 carries imprisonment up to 3 years and fine; ₹50,000 to ₹10 lakhs carries 3-5 years and fine; above ₹10 lakhs carries 7 years and fine.",
  "section 324 bns": "Section 324 of the Bharatiya Nyaya Sanhita defines forgery as making a false document or electronic record with intent to cause damage or injury, or to support any claim or title, or to cause any person to part with property. Punishment is imprisonment up to 3 years and fine.",
  "section 351 bns": "Section 351 of the Bharatiya Nyaya Sanhita defines defamation as making or publishing imputations concerning any person, intending to harm their reputation. Exceptions include truth for public good and fair comment on public conduct. Punishment under Section 353 is imprisonment up to 2 years, or fine, or both.",
  "section 124 bns": "Section 124 of the Bharatiya Nyaya Sanhita addresses terrorist acts, defining them as acts intended to threaten India's unity, integrity, security, or sovereignty, or to strike terror among people. Punishment is death or imprisonment for life, along with fine. This section consolidates provisions previously spread across multiple laws.",
  "section 69 bns": "Section 69 of the Bharatiya Nyaya Sanhita provides punishment for murder, which is death or imprisonment for life, along with fine. The section directly corresponds to the previous Section 302 of the IPC but with updated language and context.",
  "section 70 bns": "Section 70 of the Bharatiya Nyaya Sanhita addresses murder by a life convict. If a person already under sentence of life imprisonment commits murder, they shall be punished with death or further imprisonment for life, along with fine.",
  "section 74 bns": "Section 74 of the Bharatiya Nyaya Sanhita addresses cruelty by husband or relatives of husband, punishable with imprisonment up to 3 years and fine. It covers both mental and physical cruelty, including harassment for dowry. This strengthens the previous Section 498A of the IPC.",
  "section 115 bns": "Section 115 of the Bharatiya Nyaya Sanhita defines an unlawful assembly as a gathering of five or more persons with a common unlawful object. Section 117 provides punishment for rioting, which is imprisonment up to 3 years, or fine, or both. Armed rioting carries enhanced penalties of up to 5 years imprisonment.",
  "section 125 bns": "Section 125 of the Bharatiya Nyaya Sanhita defines assault as making any gesture or preparation that causes a person to apprehend that criminal force will be applied. Section 126 provides punishment of imprisonment up to 3 months, or fine up to ₹500, or both.",
  "section 305 bns": "Section 305 of the Bharatiya Nyaya Sanhita addresses theft after preparation for causing death, hurt, or restraint to facilitate the theft. Punishment is rigorous imprisonment up to 10 years and fine. This is an enhancement of the previous Section 382 of the IPC.",
  "section 330 bns": "Section 330 of the Bharatiya Nyaya Sanhita addresses criminal breach of trust, punishable with imprisonment up to 3 years, or fine, or both. For carriers, warehouse keepers, bankers, merchants, or agents, punishment is enhanced to 7 years imprisonment and fine.",

  // Additional Legal Concepts
  "legal aid": "Free legal aid in India is available through Legal Services Authorities at National, State, District, and Taluk levels under the Legal Services Authorities Act, 1987. Eligible beneficiaries include women, children, persons with disabilities, victims of trafficking, industrial workmen, SC/ST members, natural disaster victims, and persons with annual income below specified limits. Contact your nearest Legal Services Authority or visit nalsa.gov.in.",
  "pro bono lawyer": "For pro bono legal assistance in India: 1) Contact your State or District Legal Services Authority, 2) Approach NGOs like Human Rights Law Network or iProBono, 3) Check with the Supreme Court Legal Services Committee or High Court Legal Services Committees, 4) Use the Department of Justice's Tele-Law service (14141), 5) Visit the nearest legal aid clinic at law schools.",
  
  // Useful legal terms
  "habeas corpus": "Habeas Corpus is a constitutional remedy under Article 32 and 226 of the Indian Constitution. It's a writ directing a person detaining another to produce the detainee before the court to examine the legality of detention. It safeguards personal liberty against unlawful detention by both state and private individuals.",
  "pil": "Public Interest Litigation (PIL) in India allows any public-spirited person to approach the Supreme Court (Article 32) or High Courts (Article 226) for protection of public interest. PILs address issues affecting public at large, particularly marginalized sections. The court can take suo moto cognizance and has relaxed traditional locus standi requirements for PILs.",
  
  // Expanded Legal Cases and Issues
  "case law": "Case law refers to the law established by the outcome of former court cases. In India, landmark judgments by the Supreme Court and High Courts shape the interpretation of laws and the Constitution. Examples include the Kesavananda Bharati case (1973) which established the Basic Structure doctrine, and the Maneka Gandhi case (1978) which expanded the interpretation of Article 21.",
  "constitutional law": "Constitutional law in India governs the interpretation and implementation of the Constitution. It includes the study of fundamental rights, directive principles, and the structure of government. Key cases include Minerva Mills v. Union of India (1980) which reinforced the supremacy of the Constitution.",
  
  // Cyber Law
  "cyber crime": "To report cybercrimes in India: 1) File a complaint on the National Cyber Crime Reporting Portal (cybercrime.gov.in), 2) Call the Cyber Crime Helpline (1930), 3) Visit the nearest Cyber Crime Police Station, 4) For financial fraud, report within 24 hours for better chance of recovering funds. Common cybercrimes include phishing, identity theft, online harassment, data breach, and financial fraud.",
  "online harassment": "For online harassment in India: 1) Preserve evidence (screenshots, URLs, messages), 2) Report to the platform, 3) File complaint on cybercrime.gov.in or call 1930, 4) File an FIR at local police station mentioning relevant sections from Bharatiya Nyaya Sanhita and IT Act Sections 66E, 67, 67A as applicable. For immediate assistance against objectionable content, use National Cybercrime Reporting Portal's 'Report & Remove' feature.",
  "data privacy": "Data privacy in India is currently governed by the Information Technology Act, 2000 and the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011. The Digital Personal Data Protection Act, 2023 provides a more comprehensive framework, giving individuals rights over their personal data and imposing obligations on data processors.",
  
  // Citizenship & Immigration
  "citizenship": "Indian citizenship can be acquired by birth, descent, registration, or naturalization under the Citizenship Act, 1955. For citizenship by registration, one must have resided in India for 7 years. For naturalization, the requirement is 12 years of residence with no more than 12 months absence during the final year. The Citizenship Amendment Act, 2019 created a pathway for certain religious minorities from Afghanistan, Bangladesh, and Pakistan.",
  "oci card": "Overseas Citizen of India (OCI) card provides: 1) Multiple-entry, multi-purpose lifelong visa to India, 2) Exemption from foreigner registration, 3) Parity with NRIs in economic, financial, and educational fields (except property and agricultural land purchases), 4) No voting rights or government jobs. Eligible applicants include former Indian citizens, their descendants up to the 4th generation, and spouses of Indian citizens/OCIs.",
  "visa types": "Common Indian visa types include: Tourist visa (up to 10 years), e-Tourist visa (1-5 years), Business visa (up to 5 years), Employment visa (duration of contract), Student visa (duration of course), Medical visa (up to 1 year), Conference visa (event duration), and Research visa (up to 5 years). Each has specific documentation requirements and restrictions.",
  
  // Wills & Succession
  "will": "A legally valid will in India requires: 1) Testator must be of sound mind and at least 21 years old, 2) Signed by the testator, 3) Attested by two or more witnesses who have seen the testator sign, 4) Witnesses should not be beneficiaries. Registration of wills is optional but recommended. For Muslims, will-making is governed by Islamic law limiting bequests to one-third of property to non-heirs.",
  "probate": "Probate is a court certificate validating a will. In India, it's mandatory in the presidency towns of Kolkata, Mumbai, and Chennai. The process involves: 1) Filing petition in the High Court or District Court with jurisdiction, 2) Submitting original will, death certificate, and other supporting documents, 3) Court issues notice to family members and publishes citation in newspaper, 4) After addressing any objections, the court grants probate.",
  
  // Consumer Rights
  "consumer rights": "Under the Consumer Protection Act, 2019, Indian consumers have the right to: 1) Safety, 2) Information, 3) Choice, 4) Redressal, 5) Consumer education, 6) Protection from unfair trade practices. Complaints can be filed at District, State, or National Consumer Disputes Redressal Commission depending on the claim amount.",
  "consumer complaint": "To file a consumer complaint: 1) Approach the business first with your grievance, 2) If unresolved, file a formal complaint with the appropriate Consumer Commission (District/State/National based on claim amount), 3) Include details of the complaint, supporting documents, and relief sought, 4) Pay the nominal fee, 5) Alternative online filing is available at edaakhil.nic.in.",
  "e-commerce rights": "For e-commerce purchases in India, consumers have rights under the Consumer Protection (E-Commerce) Rules, 2020, including: 1) Clear information about sellers, products, and prices, 2) Cancellation rights, 3) Refund policies, 4) Grievance redressal mechanism, 5) Protection from unfair trade practices like fake reviews. Platforms cannot manipulate prices or misrepresent quality.",
  
  // Employment Law
  "employment": "Employment in India is governed by various laws including the Industrial Disputes Act, Factories Act, Payment of Wages Act, and more recently, the Code on Wages, 2019. These laws cover minimum wages, working hours (typically 48 hours/week), overtime payment, leave entitlement, termination procedures, and social security benefits.",
  "maternity benefits": "Under the Maternity Benefit (Amendment) Act, 2017, working women in India are entitled to: 1) 26 weeks of paid maternity leave for the first two children (12 weeks for third child onwards), 2) 12 weeks for adoptive and commissioning mothers, 3) Work-from-home options post-leave, 4) Crèche facilities in establishments with 50+ employees, 5) No termination during pregnancy/maternity leave.",
  "sexual harassment": "Workplace sexual harassment in India is addressed by the Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013. Every organization with 10+ employees must have an Internal Complaints Committee. Complaints should be filed within 3 months of the incident. Employers must provide a safe working environment and display the consequences of sexual harassment prominently.",
  
  // Casual Phrases and Greetings
  "hello": "Hello! I'm your AI legal assistant. How can I help you with legal information today?",
  "hi": "Hi there! How can I assist you with legal matters today?",
  "how are you": "I'm functioning well, thank you! I'm here to provide legal information based on Indian law. What can I help you with?",
  "thank you": "You're welcome! If you have more legal questions in the future, feel free to ask.",
  "thanks": "You're welcome! Happy to help with any more legal questions.",
  "bye": "Goodbye! If you have more legal questions later, feel free to return.",
  
  // Recent Law Updates
  "new laws": "Recent significant Indian laws include: The Digital Personal Data Protection Act, 2023; The Bharatiya Nyaya Sanhita, 2023 (replacing IPC); The Bharatiya Nagarik Suraksha Sanhita, 2023 (replacing CrPC); The Bharatiya Sakshya Adhiniyam, 2023 (replacing Indian Evidence Act); and The Telecommunications Act, 2023.",
  
  // Bharatiya Nyaya Sanhita (BNS) - New Criminal Code
  "bharatiya nyaya sanhita": "The Bharatiya Nyaya Sanhita (BNS), 2023 replaces the Indian Penal Code, 1860. It consists of 358 sections across 8 chapters, modernizing criminal law in India. Key changes include: new definitions of terrorism and organized crime, specific provisions for mob lynching (Section 103), expanded sexual offenses, increased punishments for corruption, and introducing community service as a punishment for minor offenses. It came into effect from July 1, 2024.",
  "bns": "The Bharatiya Nyaya Sanhita (BNS), 2023 replaces the Indian Penal Code, 1860. It consists of 358 sections across 8 chapters, modernizing criminal law in India. Key changes include: new definitions of terrorism and organized crime, specific provisions for mob lynching (Section 103), expanded sexual offenses, increased punishments for corruption, and introducing community service as a punishment for minor offenses. It came into effect from July 1, 2024.",
  
  // Bharatiya Nagarik Suraksha Sanhita (BNSS) - New Criminal Procedure Code
  "bharatiya nagarik suraksha sanhita": "The Bharatiya Nagarik Suraksha Sanhita (BNSS), 2023 replaces the Criminal Procedure Code, 1973. It modernizes procedural criminal law with provisions for electronic FIRs, mandatory videography of crime scenes, zero FIR filing at any police station, time limits for trials, and incorporation of technology in criminal justice processes. The BNSS aims to improve efficiency and fairness in criminal proceedings. It came into effect from July 1, 2024.",
  "bnss": "The Bharatiya Nagarik Suraksha Sanhita (BNSS), 2023 replaces the Criminal Procedure Code, 1973. It modernizes procedural criminal law with provisions for electronic FIRs, mandatory videography of crime scenes, zero FIR filing at any police station, time limits for trials, and incorporation of technology in criminal justice processes. The BNSS aims to improve efficiency and fairness in criminal proceedings. It came into effect from July 1, 2024.",
  "zero fir": "Zero FIR is a provision under the Bharatiya Nagarik Suraksha Sanhita (BNSS) that allows filing of an FIR at any police station, regardless of jurisdiction where the crime occurred. After preliminary investigation, the case is transferred to the appropriate police station. This ensures immediate registration of cases and prevents delays due to jurisdictional issues.",
  "section 173 bnss": "Section 173 of the Bharatiya Nagarik Suraksha Sanhita provides for the mandatory videography of crime scenes in certain offenses, including those punishable with 7+ years imprisonment. This provision aims to improve evidence collection and preservation, reducing the chance of evidence tampering and strengthening prosecution.",
  "section 177 bnss": "Section 177 of the Bharatiya Nagarik Suraksha Sanhita requires investigating officers to file status reports on investigation of offenses every 90 days to the Magistrate. This promotes accountability and timely completion of investigations while allowing judicial oversight of the investigation process.",
  
  // Bharatiya Sakshya Adhiniyam (BSA) - New Evidence Act
  "bharatiya sakshya adhiniyam": "The Bharatiya Sakshya Adhiniyam (BSA), 2023 replaces the Indian Evidence Act, 1872. It modernizes evidence law to incorporate electronic and digital evidence, streamlines the admissibility of electronic records, recognizes modern forensic techniques, and provides for the admissibility of scientific evidence. The BSA maintains the core principles of evidence law while updating them for the digital age. It came into effect from July 1, 2024.",
  "bsa": "The Bharatiya Sakshya Adhiniyam (BSA), 2023 replaces the Indian Evidence Act, 1872. It modernizes evidence law to incorporate electronic and digital evidence, streamlines the admissibility of electronic records, recognizes modern forensic techniques, and provides for the admissibility of scientific evidence. The BSA maintains the core principles of evidence law while updating them for the digital age. It came into effect from July 1, 2024.",
  "section 79 bsa": "Section 79 of the Bharatiya Sakshya Adhiniyam provides comprehensive guidelines for the admissibility of electronic evidence, including requirements for certification, chain of custody, and authentication. This modernized provision makes it easier to use digital evidence while ensuring its reliability and authenticity in court proceedings.",
  "section 57 bsa": "Section 57 of the Bharatiya Sakshya Adhiniyam addresses the admissibility of forensic science reports as evidence. It recognizes various modern forensic techniques and procedures for collecting and analyzing evidence, providing a legal framework for using scientific methods in criminal investigations and trials.",
  
  // Additional BNS sections with detailed punishments and descriptions
  "section 106 bns": "Section 106 of the Bharatiya Nyaya Sanhita criminalizes causing death by negligence. Punishment is imprisonment up to 5 years, or fine, or both. This applies to cases like fatal road accidents due to negligent driving and death caused by medical negligence. The section emphasizes the duty of care expected in professional and everyday activities.",
  "section 107 bns": "Section 107 of the Bharatiya Nyaya Sanhita addresses abetment to suicide. Punishment is imprisonment up to 10 years and fine. For abetment to suicide of a minor or a person of unsound mind, imprisonment extends from 10 years to life. This modernizes the previous Section 306 of the IPC with enhanced penalties for vulnerable victims.",
  "section 108 bns": "Section 108 of the Bharatiya Nyaya Sanhita criminalizes attempt to murder. Punishment is imprisonment up to 10 years and fine. The section applies even if no harm results, as long as the intention or knowledge to cause death exists. This updates Section 307 of the former IPC with clearer language on attempts.",
  "section 111 bns": "Section 111 of the BNS addresses voluntarily causing grievous hurt. Punishment is imprisonment up to 7 years and fine. 'Grievous hurt' includes permanent privation of sight or hearing, emasculation, permanent disfiguration of face, fracture or dislocation of bone or tooth, and any hurt endangering life.",
  "section 127 bns": "Section 127 of the Bharatiya Nyaya Sanhita addresses organized crime. It defines organized crime as continuing unlawful activities by individuals or groups using violence or coercion for economic or other benefits. Punishment is imprisonment for life or minimum 5 years imprisonment and fine minimum ₹5 lakhs. This is a new provision not present in the IPC.",
  "section 130 bns": "Section 130 of the BNS defines terrorist act as any act intended to threaten the unity, integrity, security, or sovereignty of India, or to strike terror in people. Punishment is death or imprisonment for life, plus fine. This consolidates and strengthens provisions previously in separate legislations.",
  
  // Removing duplicate entries (fixing the errors)
  "section 140_bns_detailed": "Section 140 of the BNS addresses kidnapping for ransom with punishment of 10 years to life imprisonment and fine. If the victim dies during captivity, punishment may extend to death. This enhances the previous Section 364A of the IPC with more severe penalties.",
  "section 153 bns": "Section 153 of the BNS criminalizes trafficking of persons. Punishment is rigorous imprisonment for 7-10 years and fine. For trafficking more than one person, punishment is 10 years to life imprisonment and fine ₹1 lakh. This consolidates various trafficking provisions from the IPC with enhanced penalties.",
  "section 166 bns": "Section 166 of the BNS addresses penetrative sexual assault on children, punishable with imprisonment of 3-5 years and fine. This section incorporates elements of the Protection of Children from Sexual Offences (POCSO) Act within the main criminal code.",
  "section 191 bns": "Section 191 of the BNS criminalizes voyeurism, defined as watching or capturing images of a woman engaged in a private act. Punishment is imprisonment of 1-3 years and fine for first conviction, and 3-7 years for subsequent convictions. This updates Section 354C of the IPC.",
  "section 211 bns": "Section 211 of the BNS addresses wrongful confinement, punishable with imprisonment up to 1 year, or fine up to ₹2,000, or both. Wrongful confinement beyond 3 days carries imprisonment up to 3 years and fine.",
  "section 224 bns": "Section 224 of the BNS criminalizes selling or manufacturing goods with false trademarks. Punishment is imprisonment up to 1 year or fine, or both. For subsequent convictions, punishment is imprisonment up to 3 years or fine, or both.",
  "section 231 bns": "Section 231 of the BNS addresses house-trespass, defined as unlawful entry into or remaining in any building used as a human dwelling or for worship. Punishment is imprisonment up to 1 year, or fine up to ₹3,000, or both.",
  "section 305_bns_detailed": "Section 305 of the BNS addresses theft after preparation for causing death or hurt. Punishment is rigorous imprisonment up to 10 years and fine. This is an enhancement of the previous Section 382 of the IPC.",
  "section 332 bns": "Section 332 of the BNS criminalizes criminal breach of trust by public servants, bankers, merchants, or agents. Punishment is imprisonment up to 10 years and fine. This updates Section 409 of the IPC with enhanced penalties.",
  "section 338 bns": "Section 338 of the BNS addresses the receiving of stolen property. Punishment is imprisonment up to 3 years, or fine, or both. If the property is valued over ₹10 lakhs, punishment is imprisonment up to 7 years and fine.",
  
  // Specific Acts and Legal Provisions
  "pocso act": "The Protection of Children from Sexual Offences (POCSO) Act, 2012 provides a comprehensive framework for protecting children from sexual assault, sexual harassment, and pornography. It establishes special courts for speedy trials, prescribes stringent punishments, and includes child-friendly procedures for reporting, recording evidence, investigation and trial. Key features include: mandatory reporting of offenses, in-camera trials, and special provisions for vulnerable children.",
  "dowry prohibition act": "The Dowry Prohibition Act, 1961 prohibits the giving, taking, or demanding of dowry. Dowry is defined as property or valuable security given in connection with marriage. Penalties include imprisonment of 5+ years and a fine of ₹15,000 or the value of dowry (whichever is higher). The Bharatiya Nyaya Sanhita's Section 69 addresses dowry deaths, and provisions against cruelty in domestic relationships.",
  "motor vehicles act": "The Motor Vehicles Act, 1988 (amended in 2019) governs all aspects of road transport vehicles in India. The 2019 amendment significantly increased penalties for traffic violations, introduced electronic monitoring of traffic rules, established a Motor Vehicle Accident Fund for victims, and created a National Road Safety Board. Key violations like drunk driving now carry fines up to ₹10,000 and/or imprisonment.",
  "juvenile justice act": "The Juvenile Justice (Care and Protection of Children) Act, 2015 addresses children in conflict with law and children in need of care and protection. For serious offenses by children aged 16-18, there's provision for trial as adults. The Act establishes Child Welfare Committees, Juvenile Justice Boards, and Children's Courts, while emphasizing rehabilitation and social reintegration.",
  "arbitration and conciliation act": "The Arbitration and Conciliation Act, 1996 (amended in 2019) provides for domestic and international commercial arbitration, conciliation, and enforcement of foreign awards. The 2019 amendment establishes an Arbitration Council of India, imposes a 12-month timeline (extendable by 6 months) for tribunal awards, and introduces provisions for the appointment of arbitrators by designated arbitral institutions.",
  "companies act": "The Companies Act, 2013 governs company formation, management, and dissolution in India. Key provisions include: mandatory Corporate Social Responsibility for eligible companies, one-person company concept, enhanced disclosure norms, mandatory rotation of auditors, stricter regulations for related party transactions, and provisions for class action suits by shareholders.",
  "income tax act": "The Income Tax Act, 1961 governs direct taxation in India. Income is categorized as: salary, house property, business/profession, capital gains, and other sources. Key features include Tax Deducted at Source (TDS), advance tax payments, deductions under Sections 80C-80U, and assessment procedures. Recent amendments have introduced simplified compliance for small taxpayers and faceless assessment schemes.",
  "gst": "Goods and Services Tax (GST) implemented in 2017 is a comprehensive indirect tax on supply of goods and services. It's a destination-based consumption tax with four main rates: 5%, 12%, 18%, and 28%. Special provisions exist for small businesses, including composition scheme for those with turnover below ₹1.5 crore. GST has subsumed multiple indirect taxes like VAT, Service Tax, and Excise Duty.",
  "patents act": "The Patents Act, 1970 (amended in 2005) governs patent protection in India. Patents are granted for inventions that are new, involve an inventive step, and have industrial application. The term is 20 years from filing date. Section 3(d) restricts evergreening of pharmaceutical patents. Compulsory licensing provisions exist for unmet public health needs and in cases of non-working of patents.",
  "copyright act": "The Copyright Act, 1957 (amended in 2012) protects literary, dramatic, musical, artistic works, films, and sound recordings. Copyright exists for 60 years after author's death or from publication for posthumous works. The 2012 amendment strengthened the rights of performers, addressed digital rights management, and introduced compulsory licensing for certain works.",
  "insolvency and bankruptcy code": "The Insolvency and Bankruptcy Code (IBC), 2016 provides time-bound resolution for insolvency, typically 180 days (extendable to 330 days). It establishes the National Company Law Tribunal as adjudicating authority, introduces a creditor-in-control model, ensures operational creditors' protection, and creates an information utility system. Recent amendments have recognized homebuyers as financial creditors.",
  "reservation policy": "India's reservation policy is based on Articles 15(4) and 16(4) of the Constitution, providing for reservation in education and public employment for Scheduled Castes (SCs), Scheduled Tribes (STs), and Other Backward Classes (OBCs). The current reservation stands at 15% for SCs, 7.5% for STs, and 27% for OBCs. The 103rd Amendment (2019) introduced 10% reservation for Economically Weaker Sections (EWS).",
  
  // Additional Acts with detailed provisions
  "domestic violence act": "The Protection of Women from Domestic Violence Act, 2005 provides civil remedies to women facing domestic violence. It defines domestic violence broadly to include physical, sexual, verbal, emotional, and economic abuse. Remedies include protection orders, residence orders, monetary relief, custody orders, and compensation orders. Domestic Violence Protection Officers assist victims, and the Act covers women in all domestic relationships, not just marriages.",
  "medical termination of pregnancy act": "The Medical Termination of Pregnancy (Amendment) Act, 2021 allows abortion up to 20 weeks with the opinion of one doctor, and up to 24 weeks for special categories of women with the opinion of two doctors. It permits abortion at any gestational period for substantial fetal abnormalities diagnosed by a Medical Board. The Act emphasizes women's choice and maintains confidentiality of women seeking abortion.",
  "succession laws": "Succession laws in India vary by religion. Hindu Succession Act governs Hindus, Buddhists, Jains, and Sikhs, with 2005 amendment giving equal rights to daughters. Muslim personal law applies to Muslims, with different rules for Sunni and Shia communities. Indian Succession Act governs Christians and Parsis. Special Marriage Act governs those married under it regardless of religion.",
  "negotiable instruments act": "The Negotiable Instruments Act, 1881 governs promissory notes, bills of exchange, and cheques. Section 138 addresses dishonor of cheques for insufficiency of funds, punishable with imprisonment up to 2 years, or fine up to twice the amount of the cheque, or both. The 2018 amendment introduces interim compensation and centralizes trial for cases filed against the same person.",
  "prevention of corruption act": "The Prevention of Corruption Act, 1988 (amended in 2018) criminalizes public servant corruption. The 2018 amendment criminalizes giving bribes (with protection for coerced bribe-givers), requires prior government approval for investigation of public servants, establishes a 4-year timeline for corruption trials, and enhances punishment to 3-7 years imprisonment.",
  "competition act": "The Competition Act, 2002 promotes competition and prevents anti-competitive practices. It prohibits anti-competitive agreements, abuse of dominant position, and regulates combinations (mergers and acquisitions) beyond specified thresholds. The Competition Commission of India enforces the Act, with powers to impose penalties up to 10% of average turnover for violations.",
  "environmental protection act": "The Environment Protection Act, 1986 authorizes the central government to protect and improve environmental quality, set standards, and regulate industry. It imposes imprisonment up to 5 years and/or fine up to ₹1 lakh for violations, with additional fine up to ₹5,000 per day for continuing offenses. The Act serves as an umbrella legislation for environmental regulation in India.",
  "right to education act": "The Right of Children to Free and Compulsory Education Act, 2009 provides free and compulsory education for children aged 6-14 years. It mandates 25% reservation in private schools for disadvantaged groups, prohibits screening procedures or capitation fees, bans corporal punishment, requires appropriate pupil-teacher ratios, and sets minimum teacher qualifications.",
  "rental laws": "Rental laws in India are primarily state-specific Rent Control Acts. The Model Tenancy Act, 2021 (adopted by some states) aims to balance landlord and tenant interests by establishing rent authorities, requiring written agreements, capping security deposits at 2 months' rent for residential properties, and providing mechanisms for dispute resolution through dedicated rent courts and tribunals.",
  "narcotics act": "The Narcotic Drugs and Psychotropic Substances Act, 1985 prohibits production, manufacture, cultivation, possession, sale, purchase, transport, and consumption of narcotic drugs and psychotropic substances. Penalties vary by quantity: small quantity (imprisonment up to 1 year), commercial quantity (imprisonment 10-20 years), and between the two (imprisonment up to 10 years).",
  "information technology act": "The Information Technology Act, 2000 provides legal recognition for electronic records and digital signatures. It criminalizes cybercrimes like hacking, identity theft, cyberstalking, and publishing obscene content online. The 2008 amendment introduced section 66A (later struck down), strengthened provisions against child pornography, and defined cybercafé obligations.",
  "right to fair compensation act": "The Right to Fair Compensation and Transparency in Land Acquisition, Rehabilitation and Resettlement Act, 2013 governs land acquisition. It requires consent (70-80% based on purpose), social impact assessment, and compensation of 2-4 times market value in rural areas and 2 times in urban areas. It also requires rehabilitation and resettlement for affected families.",
  "forest conservation act": "The Forest Conservation Act, 1980 restricts the use of forest land for non-forest purposes and prevents deforestation. Prior approval from the central government is required for diversion of forest land. Compensatory afforestation is mandatory. Violations are punishable with imprisonment up to 15 days. The 2023 amendment exempts certain categories of land from the Act's provisions.",
  "prevention of money laundering act": "The Prevention of Money Laundering Act, 2002 criminalizes money laundering with imprisonment of 3-7 years and fine, going up to 10 years for certain categories. It establishes procedures for confiscation of property derived from money laundering, creates obligations for banking companies and financial institutions for verification and record-keeping, and establishes a Financial Intelligence Unit.",
  "trade marks act": "The Trade Marks Act, 1999 provides for registration and protection of trade marks for goods and services. Registration gives exclusive rights to use the mark for 10 years (renewable). Infringement remedies include injunctions, damages, and account of profits. Criminal penalties for applying false trade marks include imprisonment up to 3 years and fine.",
  
  // Data Protection and Digital Laws
  "data protection act": "The Digital Personal Data Protection Act, 2023 was enacted on August 11, 2023. It establishes a framework for processing digital personal data, protecting individuals' privacy while enabling lawful data processing. Key features include: consent-based data processing, purpose limitation, data minimization, accuracy requirements, storage limitation, and security measures. It also establishes a Data Protection Board of India.",
  "digital india act": "The Digital India Act (currently in draft stage) aims to replace the IT Act, 2000 and provide a comprehensive framework for governing digital technology, internet, and cybersecurity. It proposes regulations for social media platforms, online gaming, AI, blockchain, IoT devices, and provisions against fake news, doxxing, and economic fraud. The draft includes protection for digital personal data and categorization of online content.",
  "it act section 66": "Section 66 of the Information Technology Act, 2000 deals with computer-related offenses. It criminalizes acts of dishonestly or fraudulently accessing computer systems, data theft, identity theft, cheating by personation using computer resources, and violation of privacy. Punishment includes imprisonment up to 3 years or fine up to ₹5 lakh, or both.",
  "it act section 67": "Section 67 of the Information Technology Act, 2000 prohibits publishing or transmitting obscene material in electronic form. The punishment is imprisonment up to 3 years and fine up to ₹5 lakh for the first conviction, and imprisonment up to 5 years and fine up to ₹10 lakh for subsequent convictions. Section 67A specifically addresses sexually explicit material with higher penalties.",
  
  // Recent Legal Topics
  "criminal law reform": "In 2023, India overhauled its criminal justice system by replacing colonial-era laws with three new codes: 1) Bharatiya Nyaya Sanhita (replacing IPC) - introduces community service as punishment, defines terrorism, and includes new provisions for mob lynching; 2) Bharatiya Nagarik Suraksha Sanhita (replacing CrPC) - mandates electronic FIRs and introduces zero FIR concept; 3) Bharatiya Sakshya Adhiniyam (replacing Indian Evidence Act) - modernizes evidence collection including electronic and digital evidence.",
  "telecommunications act": "The Telecommunications Act, 2023 replaces the 138-year-old Indian Telegraph Act. It simplifies licensing, recognizes spectrum as a valuable resource, creates a non-auction pathway for satellite broadband, establishes a Digital Bharat Nidhi (fund for rural connectivity), includes right of way provisions, and enhances user protection with stringent KYC requirements.",
  "mediation act": "The Mediation Act, 2023 promotes mediation as an alternative dispute resolution mechanism. It mandates pre-litigation mediation in certain cases, establishes the Mediation Council of India as a regulatory body, provides for enforcement of mediated settlement agreements, and includes online mediation provisions.",
  "insolvency bankruptcy code amendment": "The Insolvency and Bankruptcy Code (Amendment) Act, 2023 improves the insolvency resolution framework by allowing admission or withdrawal of insolvency applications with approval from 90% of creditors, streamlining the Corporate Insolvency Resolution Process, and addressing delays in admission of applications.",
  "waqf amendment bill": "The Waqf (Amendment) Bill, 2024 proposes significant changes to the Waqf Act, 1995, including renaming the 'Waqf Board' to 'Bharat Waqf Board', establishing a Central Waqf Council with broader representation, and requiring documentary evidence for property registration as waqf property. The bill is currently under parliamentary consideration.",
  
  // New Legal Topics and Keywords
  "culpable homicide": "Culpable homicide under Section 104 of the Bharatiya Nyaya Sanhita is causing death with the intention of causing death or causing bodily injury likely to cause death, but without the premeditation or additional circumstances that would make it murder. Punishment is imprisonment up to 10 years and fine, or imprisonment for life if done with the intention of causing death.",
  "cheating": "Cheating under Section 318 of the Bharatiya Nyaya Sanhita is defined as fraudulently or dishonestly inducing a person to deliver property or consent to property delivery. Punishment varies based on the amount involved: up to ₹50,000 carries imprisonment up to 3 years; ₹50,000 to ₹10 lakhs carries 3-5 years; above ₹10 lakhs carries 7 years, all with fine.",
  "criminal intimidation": "Criminal intimidation under Section 351 of the Bharatiya Nyaya Sanhita is threatening a person with injury to cause alarm or to force them to do or omit any act. Punishment is imprisonment up to 2 years, or fine, or both. If the threat is to cause death or grievous hurt, or to destroy property by fire, punishment is imprisonment up to 7 years and fine.",
  "sedition": "The offense of sedition, previously under Section 124A of the IPC, has been removed from the Bharatiya Nyaya Sanhita. It has been replaced with Section 152, which addresses acts endangering sovereignty, unity and integrity of India. This section is more specific and requires an act involving threats of violence or disruption of public order.",
  "trafficking": "Human trafficking under Section 153 of the Bharatiya Nyaya Sanhita carries punishment of rigorous imprisonment for 7-10 years and fine. For trafficking of more than one person, punishment is 10 years to life imprisonment and fine of at least ₹1 lakh. For repeat offenders, punishment is life imprisonment with fine of ₹2 lakhs.",
  "child abuse": "Child abuse is addressed under multiple provisions of the Bharatiya Nyaya Sanhita and the POCSO Act, 2012. BNS Section 166 covers penetrative sexual assault on children with punishment of 3-5 years imprisonment and fine. BNS Section 80 addresses using children for vending, peddling, or smuggling intoxicating or narcotic drugs or psychotropic substances, punishable with 7-10 years imprisonment and fine.",
  "hit and run": "Hit and run cases under Section 106 of the Bharatiya Nyaya Sanhita (causing death by negligence) carry punishment of imprisonment up to 5 years and fine. For accidents causing deaths under Section 106, the BNS mandates forensic and vehicular examination, supported by the Motor Vehicles Act provisions for compensation to victims.",
  "stalking": "Stalking under Section 78 of the Bharatiya Nyaya Sanhita is punishable with imprisonment up to 3 years and fine for first conviction, and imprisonment up to 5 years and fine for subsequent convictions. The offense includes following a woman, contacting her despite clear disinterest, monitoring her internet or electronic communication, or watching her movements.",
  "cyberbullying": "Cyberbullying is addressed under various provisions of the Information Technology Act and the Bharatiya Nyaya Sanhita. IT Act Section 66E (violation of privacy) and Section 67 (obscene material) apply to cyberbullying cases. BNS provisions on defamation (Section 351), criminal intimidation (Section 352), and insulting the modesty of women (Section 78) can also apply to cyberbullying.",
  "mob lynching": "Mob lynching is specifically addressed under Section 103 of the Bharatiya Nyaya Sanhita, defined as an act of violence by a group acting as vigilantes for enforcement of justice. Punishment ranges from 7 years imprisonment to life imprisonment, depending on the severity of harm caused to the victim. This is a new provision not present in the previous IPC.",
  "honor killing": "Honor killing is covered under murder (Section 103 of the BNS), with punishment of death or imprisonment for life, plus fine. The Supreme Court has issued guidelines for prevention and punishment of honor killings, directing states to identify districts where honor killings occur and take preventive measures, including protection to couples who marry against their families' wishes.",
  "terrorism": "Terrorism under Section 124 of the Bharatiya Nyaya Sanhita is defined as acts intended to threaten India's unity, integrity, security, or sovereignty, or to strike terror among people. Punishment is death or imprisonment for life, plus fine. The section consolidates provisions previously spread across multiple laws including the Unlawful Activities Prevention Act.",
  "drugs offenses": "Drug offenses are primarily governed by the Narcotic Drugs and Psychotropic Substances Act, 1985. Penalties vary based on quantity: small quantity (imprisonment up to 1 year, fine up to ₹10,000), commercial quantity (rigorous imprisonment 10-20 years, fine ₹1-2 lakh), and between the two (rigorous imprisonment up to 10 years, fine up to ₹1 lakh).",
  "white collar crimes": "White collar crimes include fraud (BNS Section 318), cheating (BNS Section 318), criminal breach of trust (BNS Section 330), forgery (BNS Section 324), tax evasion, insider trading, and money laundering. Punishments vary: fraud involving over ₹10 lakhs carries 7 years imprisonment, criminal breach of trust by public servants carries 10 years imprisonment.",
  "cybercrimes": "Cybercrimes are addressed under the Information Technology Act, 2000 and the Bharatiya Nyaya Sanhita. Common cybercrimes include hacking (Section 66 IT Act), identity theft (Section 66C IT Act), cyber terrorism (Section 66F IT Act), online defamation (BNS Section 351), and online fraud (BNS Section 318). Punishments range from 3 years to life imprisonment based on the offense.",
};

export default legalKnowledgeBase;
